* [AX620Q KVM] Mount bootfs

diff --git a/build/projects/AX620Q_nand_arm32_k419_sipeed_nanokvm/Makefile b/build/projects/AX620Q_nand_arm32_k419_sipeed_nanokvm/Makefile
--- a/build/projects/AX620Q_nand_arm32_k419_sipeed_nanokvm/Makefile
+++ b/build/projects/AX620Q_nand_arm32_k419_sipeed_nanokvm/Makefile
@@ -32,8 +32,10 @@ MAKE_SQUASHFS     := $(TOOLS_PATH)/mksquashfs/mksquashfs
 PROJECT_MAK       := $(BUILD_PATH)/projects/$(PROJECT)/project.mak
 
 #boot
-DST_BOOTFS_DIR           := $(OUT_DIR)/bootfs
-BOOTFS_IMG               := $(IMAGE_OUTDIR)/bootfs.fat32
+DST_BOOTFS_DIR           	:= $(OUT_DIR)/bootfs
+BOOTFS_UBI_IMG				:= $(IMAGE_OUTDIR)/bootfs.ubifs
+BOOTFS_IMG					:= $(IMAGE_OUTDIR)/bootfs.ubi
+bootfs_img_size   := $(call KM2Bytes,$(BOOTFS_PARTITION_SIZE))
 
 #buildroot_rootfs
 BUILDROOT_VERSION           := buildroot-2025.11
@@ -52,9 +54,9 @@ DST_ROOTFS_DIR    := $(OUT_DIR)/rootfs
 endif
 
 ROOTFS_IMG        := $(IMAGE_OUTDIR)/rootfs_soc_opt.ubi
-ROOTFS_UBI_IMG    := rootfs.ubifs
-SOC_UBI_IMG       := soc.ubifs
-OPT_UBI_IMG       := opt.ubifs
+ROOTFS_UBI_IMG    := $(IMAGE_OUTDIR)/rootfs.ubifs
+SOC_UBI_IMG       := $(IMAGE_OUTDIR)/soc.ubifs
+OPT_UBI_IMG       := $(IMAGE_OUTDIR)/opt.ubifs
 rootfs_img_size   := $(call KM2Bytes,$(ROOTFS_PARTITION_SIZE))
 MODIFY_FSTAB_FILE := $(BUILD_PATH)/tools/modify_fstab.sh
 OUT_FSTAB_FILE    := $(DST_ROOTFS_DIR)/etc/fstab
@@ -67,12 +69,16 @@ DST_SOC_DIR       := $(DST_ROOTFS_DIR)/soc
 
 #opt
 SRC_OPT_DIR       := $(HOME_PATH)
+ifeq ($(use_buildroot_rootfs),yes)
+DST_OPT_DIR       := $(DST_ROOTFS_DIR)/opt
+else
 DST_OPT_DIR       := $(OUT_DIR)/opt
+endif
 
 #param
 DST_PARAM_DIR     := $(OUT_DIR)/param
 PARAM_IMG         := $(IMAGE_OUTDIR)/param.ubi
-PARAM_UBI_IMG     := param.ubifs
+PARAM_UBI_IMG     := $(IMAGE_OUTDIR)/param.ubifs
 param_img_size    := $(call KM2Bytes,$(PARAM_PARTITION_SIZE))
 
 #optee
@@ -126,6 +132,41 @@ else
 	@$(MKDIR) $(IMAGE_OUTDIR)
 	@bash mk_buildroot_rootfs_sipeed.sh $(DST_BUILDROOT_ROOTFS_DIR) $(SRC_BUILDROOT_ROOTFS_DIR)
 	@python3 $(COPY_FILE) $(PROJECT) $(PROJECT_MAK) $(SRC_ROOTFS_DIR) buildroot_rootfs.filelist $(DST_BUILDROOT_ROOTFS_DIR)
+#soc
+	@python3 $(COPY_FILE) $(PROJECT) $(PROJECT_MAK) $(SRC_SOC_DIR) soc.filelist $(DST_SOC_DIR)
+	@chmod 755 $(DST_SOC_DIR)/scripts/*.sh
+ifneq ($(strip $(CMM_POOL_PARAM)),)
+	@sed -i "s/cmmpool*=.*/cmmpool=$(CMM_POOL_PARAM)/g" $(DST_SOC_DIR)/scripts/auto_load_all_drv.sh
+endif
+ifeq ($(debug), yes)
+	@python3 $(COPY_DEBUG) $(DEBUG_SO_PATH) $(DEBUG_SO_TYPE) $(DST_SO_PATH) $(DST_SO_TYPE)
+	@python3 $(COPY_DEBUG) $(DEBUG_KO_PATH) $(DEBUG_KO_TYPE) $(DST_KO_PATH) $(DST_KO_TYPE)
+endif
+ifeq ($(SUPPORT_CPIO),TRUE)
+	@cd $(DST_BUILDROOT_ROOTFS_DIR) && find . | cpio -o -H newc > $(IMAGE_OUTDIR)/rootfs.cpio
+endif
+#opt
+	@$(ECHO) -e $(GREEN) "making $@ ..." $(DONE)
+ifeq ($(asan), yes)
+	@mkdir -p $(DST_OPT_DIR)/lib
+	@cp -rf $(CROSS_LIB_PATH)/libasan*.so* $(DST_OPT_DIR)/lib
+endif
+	@mkdir -p $(DST_OPT_DIR)/etc/models/aiisp
+	@python3 $(COPY_FILE) $(PROJECT) $(PROJECT_MAK) $(SRC_OPT_DIR) opt.filelist $(DST_OPT_DIR)
+	@for element in $(SENSOR_TYPE); do \
+		if [ ! -d $(CUR_DIR)/sensors/$$element ]; then \
+			echo "Error: Unsupported sensor: $$element"; \
+			exit 1; \
+		fi; \
+		python3 $(COPY_FILE) $(PROJECT) $(PROJECT_MAK) $(SRC_OPT_DIR) $(CUR_DIR)/sensors/$$element/so.filelist $(DST_OPT_DIR); \
+		python3 $(COPY_FILE) $(PROJECT) $(PROJECT_MAK) $(SRC_OPT_DIR) $(CUR_DIR)/sensors/$$element/model.filelist $(DST_OPT_DIR); \
+	done
+	@mkdir -p $(DST_OPT_DIR)/data
+	@mkdir -p $(DST_OPT_DIR)/usr/bin
+ifeq ($(SUPPORT_VALGRIND), yes)
+	@cp -rf $(VALGRIND_PATH)/bin/* $(DST_OPT_DIR)/bin
+	@cp -rf $(VALGRIND_PATH)/libexec $(DST_OPT_DIR)/
+endif
 ifneq ($(findstring yes, $(debugkconfig) $(debug)),)
 	echo "/soc/scripts/kmemleak_scan.sh &" >> $(DST_BUILDROOT_ROOTFS_DIR)/etc/init.d/rcS
 endif
@@ -177,66 +218,20 @@ image: rootfs_image param_image bootfs_image
 
 bootfs_image:
 	@$(ECHO) -e $(GREEN) "making $@ ..." $(DONE)
-	@partsize_m=$$(echo $(BOOT_PARTITION_SIZE) | sed 's/M//g');\
-	dd if=/dev/zero of=$(BOOTFS_IMG) bs=1M count=$$partsize_m
-	mkfs.vfat -F 32 -n BOOT $(BOOTFS_IMG)
-	mkdir -p /tmp/boot_mount
-	fusefat -o rw+ $(BOOTFS_IMG) /tmp/boot_mount
-	cp -rf $(DST_BOOTFS_DIR)/* /tmp/boot_mount/
-	fusermount -u /tmp/boot_mount
 
 rootfs_image:
 ifeq ($(strip $(use_buildroot_rootfs)),yes)
 ##### create buildroot rootfs image
 	@$(ECHO) -e $(GREEN) "making buildroot $@ ..." $(DONE)
-#soc
-	@python3 $(COPY_FILE) $(PROJECT) $(PROJECT_MAK) $(SRC_SOC_DIR) soc.filelist $(DST_SOC_DIR)
-	@chmod 755 $(DST_SOC_DIR)/scripts/*.sh
-ifneq ($(strip $(CMM_POOL_PARAM)),)
-	@sed -i "s/cmmpool*=.*/cmmpool=$(CMM_POOL_PARAM)/g" $(DST_SOC_DIR)/scripts/auto_load_all_drv.sh
-endif
-ifeq ($(debug), yes)
-	@python3 $(COPY_DEBUG) $(DEBUG_SO_PATH) $(DEBUG_SO_TYPE) $(DST_SO_PATH) $(DST_SO_TYPE)
-	@python3 $(COPY_DEBUG) $(DEBUG_KO_PATH) $(DEBUG_KO_TYPE) $(DST_KO_PATH) $(DST_KO_TYPE)
-endif
-ifeq ($(SUPPORT_CPIO),TRUE)
-	@cd $(DST_BUILDROOT_ROOTFS_DIR) && find . | cpio -o -H newc > $(IMAGE_OUTDIR)/rootfs.cpio
-endif
-#opt
-	@$(ECHO) -e $(GREEN) "making $@ ..." $(DONE)
-ifeq ($(asan), yes)
-	@mkdir -p $(DST_OPT_DIR)/lib
-	@cp -rf $(CROSS_LIB_PATH)/libasan*.so* $(DST_OPT_DIR)/lib
-endif
-	@mkdir -p $(DST_OPT_DIR)/etc/models/aiisp
-	@python3 $(COPY_FILE) $(PROJECT) $(PROJECT_MAK) $(SRC_OPT_DIR) opt.filelist $(DST_OPT_DIR)
-	@for element in $(SENSOR_TYPE); do \
-		if [ ! -d $(CUR_DIR)/sensors/$$element ]; then \
-			echo "Error: Unsupported sensor: $$element"; \
-			exit 1; \
-		fi; \
-		python3 $(COPY_FILE) $(PROJECT) $(PROJECT_MAK) $(SRC_OPT_DIR) $(CUR_DIR)/sensors/$$element/so.filelist $(DST_OPT_DIR); \
-		python3 $(COPY_FILE) $(PROJECT) $(PROJECT_MAK) $(SRC_OPT_DIR) $(CUR_DIR)/sensors/$$element/model.filelist $(DST_OPT_DIR); \
-	done
-	@mkdir -p $(DST_OPT_DIR)/data
-	@mkdir -p $(DST_OPT_DIR)/usr/bin
-ifeq ($(SUPPORT_VALGRIND), yes)
-	@cp -rf $(VALGRIND_PATH)/bin/* $(DST_OPT_DIR)/bin
-	@cp -rf $(VALGRIND_PATH)/libexec $(DST_OPT_DIR)/
-endif
 #image
 	@$(MKFS_UBIFS) -F -q -r $(DST_BUILDROOT_ROOTFS_DIR) -m 2048 -e 126976 -c 2047 -o $(ROOTFS_UBI_IMG)
-	@$(MKFS_UBIFS) -F -q -r $(DST_SOC_DIR) -m 2048 -e 126976 -c 2047 -o $(SOC_UBI_IMG)
-	@$(MKFS_UBIFS) -F -q -r $(DST_OPT_DIR) -m 2048 -e 126976 -c 2047 -o $(OPT_UBI_IMG)
+	@$(MKFS_UBIFS) -F -q -r $(DST_BOOTFS_DIR) -m 2048 -e 126976 -c 30 -o $(BOOTFS_UBI_IMG)
 	@$(MK_UBINIZE) -o $(ROOTFS_IMG) -m 2048 -p 128KiB ubi/ubinize_1Gb.cfg
 	@imgsize=$$(stat -c %s $(ROOTFS_IMG));\
 	if [ $$imgsize -gt $(rootfs_img_size) ]; then \
 		echo "Error: $(ROOTFS_IMG) file size($$imgsize bytes) exceeds $(strip $(rootfs_img_size)) bytes"; \
 		exit 1; \
 	fi
-	@cp -rf $(ROOTFS_UBI_IMG) $(IMAGE_OUTDIR)
-	@cp -rf $(SOC_UBI_IMG) $(IMAGE_OUTDIR)
-	@cp -rf $(OPT_UBI_IMG) $(IMAGE_OUTDIR)
 else
 ##### create rootfs image
 	@$(ECHO) -e $(GREEN) "making $@ ..." $(DONE)
@@ -285,9 +280,6 @@ endif
 		echo "Error: $(ROOTFS_IMG) file size($$imgsize bytes) exceeds $(strip $(rootfs_img_size)) bytes"; \
 		exit 1; \
 	fi
-	@cp -rf $(ROOTFS_UBI_IMG) $(IMAGE_OUTDIR)
-	@cp -rf $(SOC_UBI_IMG) $(IMAGE_OUTDIR)
-	@cp -rf $(OPT_UBI_IMG) $(IMAGE_OUTDIR)
 endif
 
 param_image:
@@ -304,7 +296,6 @@ param_image:
 		echo "Error: $(PARAM_IMG) file size($$imgsize bytes) exceeds $(strip $(param_img_size)) bytes"; \
 		exit 1; \
 	fi
-	@cp -rf $(PARAM_UBI_IMG) $(IMAGE_OUTDIR)
 
 clean:
 	@$(ECHO) -e $(GREEN) "rootfs $@..." $(DONE)
